apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vals-operator.fullname" . }}
  labels:
    {{- include "vals-operator.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "vals-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "vals-operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "vals-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.args }}
          args:
            {{- toYaml .Values.args | nindent 12 }}
          {{- end }}
          {{- if .Values.environmentSecret }}
          envFrom:
            - secretRef:
                name: "{{ .Values.environmentSecret }}"
          {{- else }}
          envFrom:
            {{- toYaml .Values.secretEnv | nindent 12 }}
          {{- end }}
          env:
          {{- if or .Values.openbao.enabled .Values.vault.enabled .Values.env }}
            {{- if .Values.openbao.enabled }}
            - name: BAO_ADDR
              value: {{ .Values.openbao.address | quote }}
            - name: BAO_SKIP_VERIFY
              value: {{ .Values.openbao.skipVerify | quote }}
            {{- if .Values.openbao.auth.kubernetes.roleId }}
            - name: BAO_ROLE_ID
              value: {{ .Values.openbao.auth.kubernetes.roleId | quote }}
            - name: BAO_KUBERNETES_MOUNT_POINT
              value: {{ .Values.openbao.auth.kubernetes.mountPoint | quote }}
            {{- end }}
            {{- if .Values.openbao.auth.approle.roleId }}
            - name: BAO_APP_ROLE
              value: {{ .Values.openbao.auth.approle.roleId | quote }}
            - name: BAO_APPROLE_MOUNT_PATH
              value: {{ .Values.openbao.auth.approle.mountPath | quote }}
            {{- if .Values.openbao.auth.approle.secretId }}
            - name: BAO_SECRET_ID
              value: {{ .Values.openbao.auth.approle.secretId | quote }}
            {{- end }}
            {{- end }}
            {{- if .Values.openbao.auth.userpass.username }}
            - name: BAO_LOGIN_USER
              value: {{ .Values.openbao.auth.userpass.username | quote }}
            - name: BAO_USERPASS_MOUNT_PATH
              value: {{ .Values.openbao.auth.userpass.mountPath | quote }}
            {{- if .Values.openbao.auth.userpass.password }}
            - name: BAO_LOGIN_PASSWORD
              value: {{ .Values.openbao.auth.userpass.password | quote }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- if .Values.vault.enabled }}
            - name: VAULT_ADDR
              value: {{ .Values.vault.address | quote }}
            - name: VAULT_SKIP_VERIFY
              value: {{ .Values.vault.skipVerify | quote }}
            {{- if .Values.vault.auth.kubernetes.roleId }}
            - name: VAULT_ROLE_ID
              value: {{ .Values.vault.auth.kubernetes.roleId | quote }}
            - name: VAULT_KUBERNETES_MOUNT_POINT
              value: {{ .Values.vault.auth.kubernetes.mountPoint | quote }}
            {{- end }}
            {{- if .Values.vault.auth.approle.roleId }}
            - name: VAULT_APP_ROLE
              value: {{ .Values.vault.auth.approle.roleId | quote }}
            - name: VAULT_APPROLE_MOUNT_PATH
              value: {{ .Values.vault.auth.approle.mountPath | quote }}
            {{- if .Values.vault.auth.approle.secretId }}
            - name: VAULT_SECRET_ID
              value: {{ .Values.vault.auth.approle.secretId | quote }}
            {{- end }}
            {{- end }}
            {{- if .Values.vault.auth.userpass.username }}
            - name: VAULT_LOGIN_USER
              value: {{ .Values.vault.auth.userpass.username | quote }}
            - name: VAULT_USERPASS_MOUNT_PATH
              value: {{ .Values.vault.auth.userpass.mountPath | quote }}
            {{- if .Values.vault.auth.userpass.password }}
            - name: VAULT_LOGIN_PASSWORD
              value: {{ .Values.vault.auth.userpass.password | quote }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- if .Values.env }}
            {{- toYaml .Values.env | nindent 12 }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.metricsPort | default 8080 }}
              name: metrics
              protocol: TCP
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.volumes }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      {{- end }}
