
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
    "helm.sh/hook": crd-install
    "helm.sh/hook-delete-policy": "before-hook-creation"
  creationTimestamp: null
  name: valssecrets.digitalis.io
spec:
  group: digitalis.io
  names:
    kind: ValsSecret
    listKind: ValsSecretList
    plural: valssecrets
    singular: valssecret
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: ValsSecret is the Schema for the valssecrets API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ValsSecretSpec defines the desired state of ValsSecret
            properties:
              data:
                additionalProperties:
                  properties:
                    encoding:
                      description: Encoding type for the secret. Only base64 supported.
                        Optional
                      type: string
                    ref:
                      description: Ref value to the secret in the format ref+backend://path
                        https://github.com/variantdev/vals
                      type: string
                  required:
                  - ref
                  type: object
                type: object
              databases:
                items:
                  properties:
                    driver:
                      description: Defines the database type
                      type: string
                    hosts:
                      description: List of hosts to connect to, they'll be tried in
                        sequence until one succeeds
                      items:
                        type: string
                      type: array
                    loginCredentials:
                      description: Credentials to access the database
                      properties:
                        namespace:
                          description: Optional namespace of the secret, default current
                            namespace
                          type: string
                        passwordKey:
                          description: Key in the secret containing the database username
                          type: string
                        secretName:
                          description: Name of the secret containing the credentials
                            to be able to log in to the database
                          type: string
                        usernameKey:
                          description: Key in the secret containing the database username
                          type: string
                      required:
                      - passwordKey
                      - secretName
                      type: object
                    passwordKey:
                      description: Key in the secret containing the database username
                      type: string
                    port:
                      description: Database port number
                      type: integer
                    userHost:
                      description: Used for MySQL only, the host part for the username
                      type: string
                    usernameKey:
                      description: Key in the secret containing the database username
                      type: string
                  required:
                  - driver
                  - hosts
                  - passwordKey
                  type: object
                type: array
              name:
                type: string
              ttl:
                format: int64
                type: integer
              type:
                type: string
            required:
            - data
            type: object
          status:
            description: ValsSecretStatus defines the observed state of ValsSecret
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
